### ISSUE TITLE
推送相关

### ISSUE THREAD

**Issue by xiaorouroudaren** [wildfirechat/uni-chat#24]
消息推送相关的demo里有吗 集成推送的流程是什么

**Comment by imndx** [comment]
0. `HBuilder X`里面选中`manifest.json`，然后选中`Push`-> `uniPush 1.0`.
1.  看下[uni-push](https://uniapp.dcloud.net.cn/unipush-v1.html)的文档
2. 部署最新[push-server](https://github.com/wildfirechat/push_server/tree/getui)
3.  仔细阅读[push-server](https://github.com/wildfirechat/push_server/blob/master/README.md)的 readme

然后，针对具体的问题进行跟帖讨论

**Comment by imndx** [comment]
如果需要是用`uniPush 2.0`，则不需要部署`push-server`，可参考他们的文档：[uniPush v2](https://zh.uniapp.dcloud.io/unipush-v2.html#)

`uniPush v1` 和 `uniPush v2` 区别，请参考[区别](https://ask.dcloud.net.cn/article/40291)

**Comment by imndx** [comment]
针对荣耀手机的说明：

目前，`uniPush`的配置里面，并没有单独配置荣耀推送的地方，需要特别处理，
```
        plus.push.getClientInfoAsync((info) => {
            let cid = info["clientid"];
            if (cid) {
                console.log('push clientId', cid);
                wfc.setDeviceToken(8, cid);  // 8，用来表示是荣耀推送
            }
        });
```

然后`push-server` 判断`pushType`是 8 的是，单独处理荣耀推送

**Comment by ISPANBIAO** [comment]
是否可以取消IM收发消息的时候对用户是否在线的判断，不论用户是否在线都调用推送服务，然后将push-server服务修改为push2云函数。

**Comment by imndx** [comment]
什么情况下会希望在线也进行推送呢？

如果一定要实现的话，可以采用 消息转发回调 来实现，你可以看下`im-server`配置文件里面，消息转发部分的注释。

`push-server`目前不支持 `[uniPush v2](https://zh.uniapp.dcloud.io/unipush-v2.html#)` ，`push-server`是完全开源的，你们可以自行对接

**Comment by imndx** [comment]
使用`unipush-v2`的大概思路如下：

1. 通过[云函数 URL 化](https://doc.dcloud.net.cn/uniCloud/http.html) 提供两个类似[push-server推送入口](https://github.com/wildfirechat/push_server/blob/6af09f4d6eb3d6f0c3d1c6f7f9f7cfb1e16cb858/src/main/java/cn/wildfirechat/push/PushController.java#L19-L27
)的 http 接口，这些接口对应的方法里面，解析参数，并调用`unipush-v2`相关的接口进行推送
2. 将相应的地址配置到 `im-server` 推送相关配置部分
