### ISSUE TITLE
用户信息问题

### ISSUE THREAD

**Issue by ZZWJY** [wildfirechat/uni-chat#26]
你好，uni-app得那个我的界面，有一个
user: store.state.contact.selfUserInfo,
这个selfUserInfo是从后端得那里来的啊
还有一个问题就是，语音提示是否允许野火IM录制音频，这个要改成自己得怎么改

**Comment by imndx** [comment]
```wfc.getUserInfo```获取用户信息，用户信息，在服务端是存在```t_user```表，但不能直接修改数据库，需要通过```api```接口进行更新。
```wfc.getUserId``` 获取自己的用户 id


否允许野火IM录制音频?

这个修改应用名就可以，看下```manifest.json```

**Comment by ZZWJY** [comment]
那后端想修改这个wfc.getUserInfo得用户信息或者说增加字段是怎么增加呢

**Comment by imndx** [comment]
可以通过[update](https://docs.wildfirechat.cn/server/admin_api/user_api.html)接口更新用户信息，另外，用 java 版本的 ```server SDK```，用那个更方便。

增加字段的话，可以将信息放到```userinfo```的```extra```字段里面，建议用```json```，方便以后扩展。
