### ISSUE TITLE
权限的描述修改

### ISSUE THREAD

**Issue by ZZWJY** [wildfirechat/uni-chat#30]
![1677302712536](https://user-images.githubusercontent.com/45352747/221340070-95db9d24-6844-4917-92e1-39264974b212.png)
你好，我想问下怎么修改相机，语音，视频的这个描述啊

**Comment by heavyrain2012** [comment]
请用hbuildx打开项目，然后打开文件manifest.json文件，找到“App权限配置”，然后页面最下面是“iOS隐私信息访问的许可描述”，在哪里修改对每个权限的许可描述
