### ISSUE TITLE
HBuilderX运行IOS模拟器，制作自定义调试基座打包失败

### ISSUE THREAD

**Issue by carolinetanxin** [wildfirechat/uni-chat#40]
**【描述】**

command+u 进行云打包，选择【自定义调试基座】，打包后控制台报错，报错日志：https://ide.dcloud.net.cn/build/errorLog/ecba6500-7ecd-11ee-884b-7f967f607249

**【提问】**
根据uni-app提供的报错日志我无法判断得出是我执行的哪一个步骤出错，请问是否有开发同学可以帮助查看进行诊断。如果需要提供其他信息请随时告知。

**Comment by imndx** [comment]
Hbuillder 原生插件页，选了插件了吗？看下[配置说明](https://github.com/wildfirechat/uni-chat#%E9%85%8D%E7%BD%AE)

**Comment by imndx** [comment]
不支持ios模拟器，请用真机测试
