### ISSUE TITLE
需要同步下原生ios的更改，ios支持设置pushtype的值，适配个推等第三方的推送。

### ISSUE THREAD

**Issue by fightroad** [wildfirechat/uni-chat#41]
如题 需要同步下原生ios的更改，ios支持设置pushtype的值，适配个推等第三方的推送。

**Comment by heavyrain2012** [comment]
插件已经修改，本地插件在 https://gitee.com/wfchat/uni-wfc-client/tree/main/nativeplugins   ，请等待我们发布版本

**Comment by fightroad** [comment]
> 插件已经修改，本地插件在 https://gitee.com/wfchat/uni-wfc-client/tree/main/nativeplugins ，请等待我们发布版本

ios可以使用推送服务自己anps推送吗？推送服务配置了p12证书  但是推送消息报bad devicetoken  应该是用的unipush获取到的devicetoken并不是真实的token 。

**Comment by heavyrain2012** [comment]
也可以用apns，只要拿到苹果的推送token就行，你们可以工单问一下个推怎么能拿到苹果的token
