### ISSUE TITLE
切换账号登录，【野火】【通讯录】【我的】界面展示异常

### ISSUE THREAD

**Issue by carolinetanxin** [wildfirechat/uni-chat#42]
**【描述】**
在hbuilderx模拟器上跑登录功能，直接【退出登录】 -> 切换账号登录 -> 发现【野火】【通讯录】【我的】信息都不会发生变更。

一定要后台清理掉app -> 重新打开app -> 登录，才可以更新信息。

**【附录】**
由于录屏文件过大，以百度云盘分享形式提交。

百度云链接: https://pan.baidu.com/s/1oOWmg7zjGzuhC31DDCbJMw 
提取码: emyj

**Comment by imndx** [comment]
直接用 demo，是否可以复现？

**Comment by carolinetanxin** [comment]
> 直接用 demo，是否可以复现？

可以，demo的话会走验证码，没有好友，无法验证【野火】【通讯录】，但【我的】可以验证，没有变化。

链接: https://pan.baidu.com/s/1N9HVjokfcLF3NNQEOzXj4Q 
提取码: jkhy
