### ISSUE TITLE
新版音视频插件在IOS16以下导致应用闪退

### ISSUE THREAD

**Issue by s8100089** [wildfirechat/uni-chat#43]
测试机型 苹果6P 苹果7P 苹果11  苹果12 最低IOS版本12.5.0  最高15.6.1 这个版本区间内均发生闪退问题

**Comment by imndx** [comment]
你好，请更新到 [0.6.0 版本](https://ext.dcloud.net.cn/plugin?id=15619)测试下

**Comment by s8100089** [comment]
插件市场最新的 是0.5.8
![image](https://github.com/wildfirechat/uni-chat/assets/57250773/0fb2841f-32a2-4512-b8fd-3efa7acec770)
