### ISSUE TITLE
打包 apk错误

### ISSUE THREAD

**Issue by chen-can** [wildfirechat/uni-chat#45]
目前vue3版本的云打包正常，但是使用本地打包会出现白屏，使用其他项目本地打包正常

**Comment by imndx** [comment]
请参考 #46 抓一个完整日志看下

**Comment by chen-can** [comment]
我说的本地打包是指离线打包 hbuildex 生成 app打包资源放在 Android studio 中不行

**Comment by imndx** [comment]
太理解你说的操作过程，生成 app 打包资源之后，怎么放到 Android Studio 中运行？

用插件工程的话，的确是可以生成 app 打包资源，然后替换插件里面的对应文件。

另外，还是需要抓日志，才能看出原因

**Comment by chen-can** [comment]
是我的问题 不好意思
