### ISSUE TITLE
缩放语音或视频通话相关问题

### ISSUE THREAD

**Issue by Gz921** [wildfirechat/uni-chat#49]
缩放语音或视频通话页面，在有浮窗的情况下，点击语音或者视频通话的图标，那个浮窗就不见了，然后再重新点击语音或者视频通话的图标没有任何反应，回不去single页面了，知道对方挂断通话后，才可继续操作...

**Comment by imndx** [comment]
最新代码，Android 端测试没问题，请问是用 Android 还是 iOS 测试的？

**Comment by Gz921** [comment]
> 最新代码，Android 端测试没问题，请问是用 Android 还是 iOS 测试的？

uni-chat  安卓！我拉了最新代码，但是还是有这个问题呀！
操作流程是这样的：
我开了两个端：用户A 和 用户B
A给B打语音通话，B接听了。然后A点击左上角缩放语音通话界面回到会话页。这个时候右边出现了语音通话的浮窗。
然后A手贱，再次点击了功能块模块中的语音通话/视频通话，此时浮窗消失，并且再也回不去通话界面（single页面），直到B挂断通话后，A才能重新叫起语音/视频通话，进入single页面。
由于我没有demo的登录账号和密码，我使用的demo仅仅是修改了config.js以及wfc_cli.js的服务器域名相关配置，其他内容完全一样

**Comment by imndx** [comment]
这是另外一个问题，和原始问题，不是同一个问题？

**Comment by Gz921** [comment]
> 这是另外一个问题，和原始问题，不是同一个问题？

是同一个问题，只不过我详细复述一遍我的操作过程....

**Comment by imndx** [comment]
OK，音视频通话过程中，再次点击音视频通话按钮时，应当操作无效，我们限制一下

**Comment by Gz921** [comment]
> OK，音视频通话过程中，再次点击音视频通话按钮时，应当操作无效，我们限制一下

您好，不知道是否修复好？我按照最新的代码修改之后，如果挂断对话，就不能再次发起对话了，挂断后没有清空currentCallSession...

**Comment by imndx** [comment]
已修复
